package com.example.serenity.navigation

const val ROUTE_LOGIN = "login"
const val ROUTE_REGISTER = "register"
const val ROUTE_DASHBOARD ="dashboard"
const val ROUTE_THERAPIST = "therapist"
const val ROUTE_ADD = "add"
const val ROUTE_SPLASH ="splashscreen"
const val ROUTE_START ="breathing"
const val ROUTE_WELCOME ="welcome"
const val ROUTE_CARE ="care"
const val ROUTE_EXERCISE ="exercise"
const val ROUTE_JOURNAL = "journal"
const val ROUTE_COMFORT="comfort"
const val ROUTE_MOOD="mood"
const val ROUTE_MEDITATE ="meditate"
const val ROUTE_PROFILE = "profile"
const val ROUTE_ACCOUNT="account"
const val ROUTE_CONTINUE="continue"
const val ROUTE_CHATBOT="chatbot"
const val ROUTE_SETTING= "Settings"
const val ROUTE_UPDATE= "update"
const val ROUTE_ADMIN= "admin_access"
const val ROUTE_VIEW="view"
const val ROUTE_LIST = "list"